In [24]:
import pandas as pd
df= pd.read_csv("shop_smart_ecommerce.csv")

In [25]:
df

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True,False

In [4]:
#df.isnull().sum()

In [26]:
df["VisitorType"].unique

<bound method Series.unique of 0        Returning_Visitor
1        Returning_Visitor
2        Returning_Visitor
3        Returning_Visitor
4        Returning_Visitor
               ...
12325    Returning_Visitor
12326    Returning_Visitor
12327    Returning_Visitor
12328    Returning_Visitor
12329          New_Visitor
Name: VisitorType, Length: 12330, dtype: object>

In [27]:
# label encoder

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Revenue"] = le.fit_transform(df["Revenue"])
df["Weekend"] = le.fit_transform(df["Weekend"])

In [28]:
df

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,0,0
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,0,0
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,0,0
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,0,0
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,1,0
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,1,0
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,1,0
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,0,0
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,1,0

In [29]:
# one hot encoding

cols=["VisitorType","Month"]

from sklearn.preprocessing import OneHotEncoder

ohe= OneHotEncoder( sparse_output=False, handle_unknown="ignore" )
encoded= ohe.fit_transform(df[cols])
encoded

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.]], shape=(12330, 13))

In [30]:
encoded_df= pd.DataFrame( encoded, columns=ohe.get_feature_names_out(cols), index=df.index )

df= pd.concat([ df.drop(columns=cols) , encoded_df ], axis=1 )

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Administrative                 12330 non-null  int64
 1   Administrative_Duration        12330 non-null  float64
 2   Informational                  12330 non-null  int64
 3   Informational_Duration         12330 non-null  float64
 4   ProductRelated                 12330 non-null  int64
 5   ProductRelated_Duration        12330 non-null  float64
 6   BounceRates                    12330 non-null  float64
 7   ExitRates                      12330 non-null  float64
 8   PageValues                     12330 non-null  float64
 9   SpecialDay                     12330 non-null  float64
 10  OperatingSystems               12330 non-null  int64
 11  Browser                        12330 non-null  int64
 12  Region                         12330 non-null  int64
 13  TrafficType                    12330 non-null  int64
 14  Weekend                        12330 non-null  int64
 15  Revenue                        12330 non-null  int64
 16  VisitorType_New_Visitor        12330 non-null  float64
 17  VisitorType_Other              12330 non-null  float64
 18  VisitorType_Returning_Visitor  12330 non-null  float64
 19  Month_Aug                      12330 non-null  float64
 20  Month_Dec                      12330 non-null  float64
 21  Month_Feb                      12330 non-null  float64
 22  Month_Jul                      12330 non-null  float64
 23  Month_June                     12330 non-null  float64
 24  Month_Mar                      12330 non-null  float64
 25  Month_May                      12330 non-null  float64
 26  Month_Nov                      12330 non-null  float64
 27  Month_Oct                      12330 non-null  float64
 28  Month_Sep                      12330 non-null  float64
dtypes: float64(20), int64(9)
memory usage: 2.7 MB

In [35]:
X= df.drop(columns=["Revenue"])
y= df["Revenue"]

In [37]:
# train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [42]:
# scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [43]:
# decision tree clasifier

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [44]:
y_pred = model.predict(X_test)

from sklearn.metrics import f1_score

print("f1_score:",f1_score( y_test , y_pred ))

f1_score: 0.5835351089588378

In [52]:
# pre pruning

max_depth=[2,3,4,5,6,7,8,9,10]

for depth in max_depth:
    model = DecisionTreeClassifier(max_depth=depth)
    model.fit(X_train, y_train)
    y_pred= model.predict(X_test)
    print(f"for max_depth:{depth}, f1_score:{f1_score( y_test , y_pred )}")

for max_depth:2, f1_score:0.5256609642301711
for max_depth:3, f1_score:0.6357615894039735
for max_depth:4, f1_score:0.648
for max_depth:5, f1_score:0.5973645680819912
for max_depth:6, f1_score:0.6321678321678321
for max_depth:7, f1_score:0.6256983240223464
for max_depth:8, f1_score:0.6224066390041494
for max_depth:9, f1_score:0.5989304812834224
for max_depth:10, f1_score:0.6091503267973856

In [49]:
min_samples_split=[5,10,15,20,25]

for split in min_samples_split:
    model = DecisionTreeClassifier( max_depth=4, min_samples_split=split )
    model.fit(X_train, y_train)
    y_pred= model.predict(X_test)
    print(f"for min_samples_split:{split}, f1_score:{f1_score( y_test , y_pred )}")

for min_samples_split:5, f1_score:0.648
for min_samples_split:10, f1_score:0.648
for min_samples_split:15, f1_score:0.648
for min_samples_split:20, f1_score:0.648
for min_samples_split:25, f1_score:0.648

In [53]:
from sklearn.model_selection import GridSearchCV

model= DecisionTreeClassifier()

param_grid={
    "max_depth":[2,3,4,5,6,7,8,9,10],
    "min_samples_leaf":[20,30,50],
    "min_samples_split":[5,10,15,20,25]
}

grid = GridSearchCV(
    model,
    param_grid,
    cv=5,
    scoring="f1"
)

grid.fit(X_train, y_train)
print("Best f1:", grid.best_score_)
print("Best params:", grid.best_params_)

Best f1: 0.6508526754654682
Best params: {'max_depth': 6, 'min_samples_leaf': 50, 'min_samples_split': 5}