In [2]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score

In [3]:
heart_df=pd.read_csv("heart.csv")
# heart_df
# heart_df.isnull()
# heart_df.isnull().sum()     # no null values
# heart_df.info()
# heart_df.columns
# heart_df.shape
#heart_df["target"].unique()     # it gives unique values
#heart_df["target"].nunique()    # no. of unique values
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
X = heart_df.drop(columns=["target"])
y = heart_df["target"]
X.head()
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [11]:
# Train test split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [12]:
X_train.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,42,1,1,120,295,0,1,162,0,0.0,2,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3

In [9]:
# Scaling

from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

# model = LogisticRegression( max_iter = 2000 )
# model.fit(X_train, y_train)
# y_pred= model.predict(X_test)

In [10]:
X_train

array([[-1.35679832,  0.72250438,  0.00809909, ...,  0.95390513,
        -0.68970073, -0.50904773],
       [ 0.38508599,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [-0.92132724,  0.72250438,  0.98808912, ..., -0.69498803,
        -0.68970073, -0.50904773],
       ...,
       [ 1.58263146,  0.72250438,  1.96807914, ..., -0.69498803,
         0.32186034, -0.50904773],
       [-0.92132724,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [ 0.92942484, -1.38407465,  0.00809909, ...,  0.95390513,
         1.33342142, -0.50904773]], shape=(242, 13))

In [13]:
model = LogisticRegression( max_iter = 2000 )
model.fit(X_train, y_train)
y_pred= model.predict(X_test)
print("Accuracy:",accuracy_score(y_test, y_pred)*100,"%")
print("Precision:", precision_score(y_test, y_pred)*100,"%")

Accuracy: 88.52459016393442 %
Precision: 87.87878787878788 %

In [16]:
# confustion matrix/ evaluation matrix

from sklearn.metrics import confusion_matrix, classification_report

cm= confusion_matrix(y_test, y_pred)
print(cm)
print( classification_report(y_test,y_pred))

[[25  4]
 [ 3 29]]
              precision    recall  f1-score   support

           0       0.89      0.86      0.88        29
           1       0.88      0.91      0.89        32

    accuracy                           0.89        61
   macro avg       0.89      0.88      0.88        61
weighted avg       0.89      0.89      0.89        61

In [21]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy:",accuracy_score(y_test,y_pred))
print("Precision:",precision_score(y_test, y_pred))
print("Recall score:", recall_score(y_test, y_pred))
print("f1_score:", f1_score(y_test, y_pred))

Accuracy: 0.8852459016393442
Precision: 0.8787878787878788
Recall score: 0.90625
f1_score: 0.8923076923076924

In [21]:
# we should make sure we have a balanced data
y_train[y_train==1]   #133
y_train[y_train==0]   #109

202    0
196    0
176    0
177    0
258    0
      ..
257    0
214    0
302    0
188    0
270    0
Name: target, Length: 109, dtype: int64

In [19]:
# model

model = LogisticRegression( max_iter = 2000 )  # max_iter 100 is not enough
model.fit( X_train , y_train )

LogisticRegression(max_iter=2000)

In [22]:
y_pred = model.predict(X_test)

In [26]:
print("Accuracy:",accuracy_score(y_test, y_pred)*100,"%")
print("Precision:", precision_score(y_test, y_pred)*100,"%")

Accuracy: 88.52459016393442 %
Precision: 87.87878787878788 %

In [27]:
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [28]:
y_test     # Actual value

179    0
228    0
111    1
246    0
60     1
      ..
249    0
104    1
300    0
193    0
184    0
Name: target, Length: 61, dtype: int64

In [30]:
# Assignment

import pandas as pd
emp_data= pd.read_csv("employee_turnover.csv")
emp_data

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
0,0.562326,0.141129,0.123989,0.347583,0.330353,0.328853,0.600933,0.315990,0.768736,0.090671,0.324786,0.669193,0.602932,0.105486,0.217344,0
1,0.017041,0.559047,0.511203,0.793908,0.423550,0.553450,0.742009,0.897146,0.380035,0.601633,0.694611,0.043271,0.800761,0.482484,0.030056,0
2,0.774699,0.604371,0.798174,0.260500,0.804034,0.131800,0.775178,0.830947,0.218726,0.972936,0.153476,0.701336,0.705275,0.023555,0.107638,1
3,0.628174,0.385249,0.230104,0.516809,0.272248,0.589249,0.482409,0.090507,0.402746,0.132842,0.305973,0.549688,0.600531,0.093620,0.168190,0
4,0.799183,0.199967,0.839029,0.247927,0.341934,0.076818,0.055356,0.680860,0.923341,0.493017,0.844094,0.793751,0.664679,0.712494,0.670000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,0.914733,0.965914,0.147215,0.686677,0.251346,0.572003,0.089679,0.127247,0.125553,0.346950,0.450783,0.754675,0.905320,0.203205,0.340194,1
1346,0.396906,0.182952,0.877941,0.824077,0.774960,0.057290,0.556719,0.235014,0.119685,0.781613,0.211581,0.500812,0.526096,0.044767,0.105962,1
1347,0.099171,0.363498,0.849120,0.462270,0.763922,0.585370,0.975760,0.557090,0.782690,0.384706,0.449095,0.270280,0.253656,0.201686,0.121381,1
1348,0.048193,0.453892,0.640611,0.335230,0.952724,0.638797,0.993664,0.801292,0.510281,0.164325,0.649934,0.151225,0.405705,0.422414,0.098286,1
1349,0.496702,0.523527,0.779612,0.320897,0.048957,0.637470,0.908619,0.587263,0.236790,0.265646,0.358821,0.870967,0.828226,0.128753,0.312521,0

In [32]:
X = emp_data.drop(columns=["Employee_Turnover"])
y = emp_data["Employee_Turnover"]

X.head()
y.head()

0    0
1    0
2    1
3    0
4    0
Name: Employee_Turnover, dtype: int64

In [33]:
# train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [36]:
y_train[y_train==1]   #547
y_train[y_train==0]   #533

755     0
109     0
1040    0
774     0
983     0
       ..
330     0
1238    0
466     0
121     0
1044    0
Name: Employee_Turnover, Length: 533, dtype: int64

In [34]:
# model

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [38]:
from sklearn.metrics import accuracy_score, precision_score

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))

Accuracy: 0.8592592592592593
Precision: 0.8717948717948718

In [ ]:
# y_pred

In [53]:
# y_test

In [64]:
# imporove accuracy (Lasso)

from sklearn.linear_model import LogisticRegression

model_l1 = LogisticRegression(penalty='l1', solver='liblinear', C=0.5)
model_l1.fit(X_train, y_train)

y_pred = model_l1.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))

Accuracy: 0.8703703703703703
Precision: 0.8813559322033898

In [63]:
# improve accuracy (Ridge)

from sklearn.linear_model import LogisticRegression

model_l2 = LogisticRegression(penalty='l2', solver='lbfgs', C=1.0)
model_l2.fit(X_train, y_train)

y_pred = model_l2.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))

Accuracy: 0.8592592592592593
Precision: 0.8717948717948718